title: jaswanth
logo: profileimage.jpg
description: "I am a software engineer with a passion for building things that make a difference. I am currently working as a software engineer at a startup in Bangalore, India. I am passionate about building scalable and reliable software systems. I am always looking for new opportunities to learn and grow."
theme: jekyll-theme-minimal

